### ISSUE TITLE
Tracking iteration count / function evaluation count in a simulation

### ISSUE THREAD

**Issue by GregVernon** [parmoo/parmoo#82]
I have a simulation

```python
my_moop.addSimulation({ 'name': "my_opt", 'm': 2, 'sim_func': evaluate_iteration, ... )
```

Where `evaluate_iteration()` needs information about its iteration id / evaluation id, to do things like create a subdirectory within which to work (e.g., to avoid temporary file name-clashing):

```python
test_name = f"evaluation_{eval_id}"
subdir = os.path.join( top_wd, test_name )
if not os.path.exists( subdir ):
    os.makedirs( subdir )
os.chdir( subdir )
```

I was wondering how I might do that with ParMOO... did I miss something in the documentation?

**Comment by GregVernon** [comment]
I should mention that I know one approach is to add a `global eval_id` and then `+=1` it within `evaluate_iteration()`, but I'm concerned about race conditions in concurrent execution.

**Comment by thchang** [comment]
Hi @GregVernon apologies for the delay in response, this got away from me --

If I understand, you need to pass the evaluation ID to the simulation each time it is called so that it creates a new work directory?

I am personally familiar with this type of requirement, but just realized that there is no easy/safe way to support it at this time.

However, it would be an easy thing to add on my end, so I will plan to do-so at the next release.

For now, you could look into using parmoo through libEnsemble (as opposed to libEnsemble through parmoo) for your parallelism needs.

I'm pretty sure they will have a way to support this:

  https://github.com/Libensemble/libensemble

And a parmoo genfunc example is here:

  https://github.com/Libensemble/libe-community-examples/blob/main/parmoo-emittance/libe_parmoo_accelerator_solver.py

You would need to talk to their team, but there should be a way to add a field to the sim_specs dictionary on line 103 so that the sim_id is passed as you need.

Alternatively, if you can wait for our next release, I'll try to add some kind of support for this in at the next release, e.g., a dictionary of hyperparameters for the simulation, which parmoo automatically populates with helpful information, such as the simulation id, random generator objects, etc.

@wildsm this should be on our to-do list once I finish the current re-factor
